iter_list=iter(["Alpha","Beta","Couta","Donna","Gamma","Erina"])
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))